---
version: '0.1'
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
matrix:
  os: [win]
  files: ["react_app_test.js","todo_test.js"]
runson: ${matrix.os}
pre:
  - npm install
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules
testSuites:
  - npx codeceptjs run $files --steps

jobLabel: [puppeteer-CodeceptJS, win, matrix]